import React from 'react';
import {createRoot} from 'react-dom/client';
import {Building2,Calculator,Check,ChevronDown,ChevronRight,FileCheck2,Landmark,Mail,MapPin,Menu,MessageCircle,Phone,ReceiptText,ShieldCheck,Sparkles,Users,WalletCards,X} from 'lucide-react';
import './styles.css';
const services=[['Personal Tax','T1 returns and personal filing support.',ReceiptText],['Corporate Tax','T2 corporate tax preparation and year-end support.',Building2],['Bookkeeping','Monthly, quarterly and catch-up bookkeeping.',Calculator],['Payroll','Payroll administration and year-end support.',Users],['GST / HST','Registration, filing and remittance support.',WalletCards],['Financial Statements','Clear reporting for your business.',Landmark],['Business Registration','Support getting your business set up.',FileCheck2],['CRA Assistance','Practical help responding to CRA matters.',ShieldCheck]];
const audiences=[['Individuals & Families','Clear personal tax support from preparation through filing.'],['Contractors & Gig Workers','Recordkeeping and tax support for independent earners.'],['Trucking & Logistics','Organized books and tax support for owner-operators.'],['Restaurants','Bookkeeping and payroll support for hospitality businesses.'],['Construction & Trades','Financial organization for trades and growing crews.'],['New Corporations','Practical support for newly incorporated businesses.']];
const faqs=[['Do you work with clients outside Brampton?','Yes. Hairouna offers virtual support to clients across Canada.'],['What should I bring for a tax appointment?','The exact documents depend on your situation. Start with your tax slips, identification and relevant receipts; Hairouna can confirm what else applies.'],['Can you help if my bookkeeping is behind?','Yes. Contact the team with the period involved and the records you currently have so the right next step can be identified.'],['Do you support incorporated businesses?','Yes. Hairouna supports corporate tax, bookkeeping, payroll, GST/HST, financial statements and related business needs.'],['Can you help with CRA questions?','Hairouna offers CRA assistance. Keep the notice or correspondence you received so the situation can be reviewed.']];
function GlassDocument(){return <div className="monolith-wrap" aria-hidden="true"><div className="monolith"><div className="chip"/><div className="form-lines">{Array.from({length:7}).map((_,i)=><i key={i}/>)}</div><div className="seal"><Check size={22}/></div><span className="vertical-word">HAIROUNA</span></div><div className="reflection"/></div>}
function Assistant({open,close}){const[t,setT]=React.useState('');const a={tax:'For personal tax filing, gather your slips, ID and relevant receipts, then contact Hairouna to confirm anything specific to your situation.',business:'Hairouna can help with corporate tax, bookkeeping, payroll, GST/HST and financial statements. A consultation can match services to your business.',books:'For monthly, quarterly or catch-up bookkeeping, Hairouna can review your records and help organize the next steps.',cra:'Keep the CRA notice or correspondence you received. Hairouna can review the situation and explain the next practical step.'};if(!open)return null;return <aside className="assistant-panel"><div className="assistant-head"><div><b>HB Assistant</b><small>Hairouna virtual receptionist</small></div><button onClick={close} aria-label="Close"><X/></button></div><div className="assistant-body"><div className="bot-msg">Hi! What can Hairouna help you with?</div><div className="assistant-options"><button onClick={()=>setT('tax')}>Personal taxes</button><button onClick={()=>setT('business')}>Business finances</button><button onClick={()=>setT('books')}>Bookkeeping</button><button onClick={()=>setT('cra')}>CRA issue</button></div>{t&&<div className="bot-msg answer">{a[t]}</div>}<div className="assistant-actions"><a href="tel:+14169081916"><Phone size={16}/>Call</a><a href="https://wa.me/14169081916" target="_blank" rel="noreferrer"><MessageCircle size={16}/>WhatsApp</a><a href="mailto:info@hairounaholdingsinc.com"><Mail size={16}/>Email</a></div><small className="assistant-note">General information only. Speak with Hairouna for advice specific to your situation.</small></div></aside>}
function App(){const[menu,setMenu]=React.useState(false),[assistant,setAssistant]=React.useState(false),[faq,setFaq]=React.useState(0);return <main><header className="nav"><a className="brand" href="#top"><span>H</span><div><b>HAIROUNA</b><small>BUSINESS SOLUTIONS INC.</small></div></a><nav className={menu?'open':''}><a href="#services">Services</a><a href="#clients">Who we help</a><a href="#about">Why Hairouna</a><a href="#faq">FAQ</a><a href="#contact">Contact</a><a className="nav-cta" href="mailto:info@hairounaholdingsinc.com?subject=Consultation%20Request">Free consultation</a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button></header>
<section className="hero" id="top"><div className="stars"/><div className="moon"/><div className="mountains back"/><div className="mountains front"/><div className="mist"/><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> BRAMPTON, ONTARIO · SERVING CANADA</div><h1>Your taxes.<br/><em>We prepare.</em><br/>You relax.</h1><p>Professional tax preparation, bookkeeping, payroll and business support for individuals and small businesses.</p><div className="actions"><a className="primary" href="mailto:info@hairounaholdingsinc.com?subject=Consultation%20Request">Book a free consultation <ChevronRight/></a><a className="secondary" href="#services">Explore services</a></div><div className="trust"><span><Check/>Plain-language guidance</span><span><Check/>Business-focused</span><span><Check/>Virtual support</span></div></div><GlassDocument/><div className="scroll">SCROLL TO EXPLORE <span>↓</span></div></section>
<section className="section intro" id="services"><div className="kicker">COMPLETE FINANCIAL SUPPORT</div><h2>One place for the financial work<br/>that keeps life and business moving.</h2><p className="lead">From personal returns to ongoing corporate support, Hairouna helps make the numbers easier to manage.</p><div className="service-grid">{services.map(([t,d,I])=><article className="glass-card" key={t}><div className="icon"><I/></div><h3>{t}</h3><p>{d}</p><a href="#contact">Get support <ChevronRight size={16}/></a></article>)}</div></section>
<section className="section audience" id="clients"><div className="kicker">BUILT AROUND REAL CLIENTS</div><h2>Your situation isn’t generic.<br/><em>Your support shouldn’t be either.</em></h2><div className="audience-row">{audiences.map(([t,d],i)=><div className="audience-card" key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="section why" id="about"><div><div className="kicker">WHY HAIROUNA</div><h2>Less financial noise.<br/>More forward motion.</h2><p className="lead">Financial work should be easier to understand, organize and act on.</p></div><div className="why-stack"><div><b>01</b><h3>Start with your situation</h3><p>Tell us what you need without having to know the accounting terminology.</p></div><div><b>02</b><h3>Get a clear path</h3><p>Identify the relevant service and information needed to move forward.</p></div><div><b>03</b><h3>Stay organized</h3><p>Keep filings, payroll and financial records visible and manageable.</p></div></div></section>
<section className="section checklist"><div className="folder"><span>2026 · CANADA</span><b>TAX<br/>CHECKLIST</b></div><div><div className="kicker">PREPARE WITH CONFIDENCE</div><h2>Know what to gather<br/>before you file.</h2><p className="lead">Use Hairouna’s Canadian tax checklist to organize common slips, receipts and filing information.</p><a className="primary" href="https://hairounaholdingsinc.com/checklist.html" target="_blank" rel="noreferrer">Open the checklist <ChevronRight/></a></div></section>
<section className="section faq-section" id="faq"><div className="faq-heading"><div className="kicker">QUESTIONS, MADE SIMPLE</div><h2>Frequently asked questions.</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={'faq-item '+(faq===i?'active':'')} key={q}><button onClick={()=>setFaq(faq===i?-1:i)} aria-expanded={faq===i}><span>{q}</span><ChevronDown/></button>{faq===i&&<p>{a}</p>}</div>)}</div></section>
<section className="section contact" id="contact"><div className="contact-panel"><div><div className="kicker">READY WHEN YOU ARE</div><h2>Let’s make the next step clear.</h2><p>Book a free, no-pressure consultation and tell Hairouna what you need help with.</p></div><div className="contact-actions"><a className="primary" href="mailto:info@hairounaholdingsinc.com?subject=Consultation%20Request">Book a consultation <ChevronRight/></a><a href="tel:+14169081916"><Phone/>(416) 908-1916</a><a href="https://wa.me/14169081916" target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp</a><a href="mailto:info@hairounaholdingsinc.com"><Mail/>Email Hairouna</a></div></div><div className="location-strip"><span><MapPin/>Brampton, Ontario, Canada</span><span>In person & virtually across Canada</span></div></section>
<footer><div className="brand"><span>H</span><div><b>HAIROUNA</b><small>BUSINESS SOLUTIONS INC.</small></div></div><p>Tax • Bookkeeping • Payroll • Business Support</p><small>© {new Date().getFullYear()} Hairouna Business Solutions Inc. All rights reserved.<br/>General information only; not professional advice.</small></footer><button className="hb" aria-label="Open HB Assistant" onClick={()=>setAssistant(true)}><span>HB</span><i/></button><Assistant open={assistant} close={()=>setAssistant(false)}/></main>}
createRoot(document.getElementById('root')).render(<App/>);
